name: "test docker"

on:
  pull_request:
  push:
  schedule:
    - cron: '15 5 * * *'

jobs:
  eval_cache:
    runs-on: ubuntu-latest
    concurrency: ${{ github.ref}}
    container:
      image: tomberek/nix-runner
      env:
        NIX_CONFIG: |
          experimental-features = nix-command flakes
          access-tokens = ${{ secrets.GITHUB_TOKEN }}
    steps:
       - name: Expose GitHub Runtime
         uses: crazy-max/ghaction-github-runtime@v1
       - name: something
         run: |
           git clone https://${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY repo && cd repo
           ls -alh
           echo hello
           nix --version
           nix run nixpkgs#hello
           env | sort
       - name: Cache multiple paths
         uses: actions/cache@v3
         with:
           path: |
             ~/.cache/nix
           key: ${{ runner.os }}-${{ hashFiles('flake.lock') }}
